### PR TITLE
README update

### PR DESCRIPTION
**Pull request by shipofgenius**
Debian install
Windows install

Troubleshooting should be moved to the wiki later. Temporary section is temporary :)
Node version should be decided on and controlled. Current Beastie runs fine on 7.10 stable.

### CODE REVIEW

**Comment by benwurth** [comment]
What? No love for OSX?  ;)

You may want to include that as well. Possibly Fedora instructions, too?

**Comment by shipofgenius** [comment]
I'll work on it. Agreed should do one for each major base distro. Where o' where am I gonna find an osx image tho!?!?1 😝

**Comment by benwurth** [comment]
In brief, the OSX installation instructions are:

#### Install
1. Install Homebrew from https://brew.sh/
2. `brew update`
3. `brew install node` (also installs npm)
4. `git clone https://github.com/teamTALIMA/BeastieBot`
5. `cd BeastieBot`
6. `npm install`

#### Setup
`cp config/secrets-example.js config/secrets.js`

`nano config/secrets.js`

#### Run
`nodejs index.js`

**Comment by scryptonite** [comment]
:thinking: as a possible alternative to specifying Node.js installation instructions, might the readme instead just link to the official Node.js binary & installer downloads and also the platform specific installation instructions that nodejs.org maintains?

I'm thinking the readme could look something like this, instead of having multiple installation instructions per platform:

--------------

## Installation, Setup and Running Beastie Bot

  1. You should have Node.js v7.10 or later installed:
     - :arrow_right: [**Download Node.js Current**](https://nodejs.org/en/download/current/) (ideal for most Windows and Mac installations)
     - :arrow_right: [**Installing Node.js via your package manager**](https://nodejs.org/en/download/package-manager/) (ideal for command line aficionados)
     - After you've installed, you should verify that you are running the latest version of node via the command line:
       💲 `node -v` &mdash; should output `v7.10.0` or newer.
  2. Clone the BeastieBot repository:
     💲 `git clone https://github.com/teamTALIMA/BeastieBot`
     - Alternatively you may [**download the repository**](https://github.com/teamTALIMA/BeastieBot/archive/master.zip) as a zip and extract it to somewhere you can easily navigate to.
  4. Change and move your command line into the BeastieBot project:
    💲 `cd path/to/BeastieBot/` &mdash; where `path/to/BeastieBot/` is the path to where BeastieBot was cloned or extracted.
  5. After you've properly configured the `secrets.js` file, install BeastieBot's required npm dependencies:
     💲 `npm install`
  6. Setup the `secrets.js` file by copying `secrets-example.js` in the `config/` directory & then opening `secrets.js` in your favorite text editor.
     - **Windows**
        - 💲 `copy config/secrets-example.js config/secrets.js`
        - 💲 `nodepad config/secrets.js`
     - **Unix**
       - 💲 `cp config/secrets-example.js config/secrets.js`
       - 💲 `nano config/secrets.js`
     - *Configuring*
       - [You can get an OAuth token by connecting your Twitch accounts here](https://twitchapps.com/tmi/)
       - [Register a Developer Application with Twitch.tv for your bot to get a `clientId`](https://www.twitch.tv/settings/connections)
         &mdash; for the purpose of being able to query the Twitch API
  7. Run BeastieBot:
     💲 `node index.js`
     - If everything is working you should see two successful authentication attempts and that Beastie joined your broadcaster's channel and announced "Hello everybody! :D I have awoken! Welcome back to `broadcaster`'s channel!".
     - You can hold `Control-C` to stop BeastieBot.

**Comment by benwurth** [comment]
@scryptonite: Seems logical enough. I think the important thing is to get this thing pulled, though, so there's at least something in the README.

@teamTALIMA, what are your thoughts on this PR?

**Comment by TalimaVale** [comment]
Thank you for improving our readme! :)

**Pull request merged**
