### PR TITLE
Custom Commands , Strawpoll , Constants

### PR DESCRIPTION
**Pull request by shipofgenius**
* Custom commands can now be created
  *  Currently set to broadcaster only
  *  !commands add !commandName MESSAGE
  *  !commands edit !commandName NEWMESSAGE
  *  !commands delete !commandName
  *  created commands are stored in commands/custom.json

* package.json - added script parameter for using nodejs in IDEs

* added broadcaster only !testcommand for development testing

* moved 
 ``` 
Object.assign(commands, raid.commands);
_.merge(commands, customCom);
```
to
 ```  mergeCommands();  ```

 in commands.js

* Updated Beastie's command chart in commands.js

### CODE REVIEW

**Comment by shipofgenius** [comment]
* created json folder
* create polls with !poll new
* !poll results will return latest poll of the channel.
* poll ids are stored in json/polls.json
* created constants file in config/constants.js 
* Awoken message can now be turned on/off in config/constants
* created a logs folder with beastie.log and chat.log. Logs are not implemeneted yet

**Comment by scryptonite** [comment]
Hey Trugamer (@shipofgenius)! 

This looks like it's going to be a really good PR but I have some things I think I would like to see addressed before merging if that is okay with you. I understand that you haven't worked on your fork of Beastie in a while so I'd also like to offer myself up to help with the following todo list if you'd like any or if you think you'll be too busy to see them through in the next few days.

- [ ] There are conflict markers in *.gitignore*. I think you meant to remove these at some point while resolving a merge conflict 😉
- [ ] The indentation is lacking or mismatching in some files. From what I can tell the indentation used throughout the project was **4 spaces**.
- [ ] Bug: Custom commands should keep the original casing when they're created, so as to preserve emotes, links and other case-sensitive things.
- [ ] The creation of a new strawpoll should result in the link being posted to the chat. Currently there is no indication to the user of the command as to what happened or how to proceed.
- [ ] Synchronous I/O calls (such as `fs.writeFileSync`) should be eliminated **or** at least eliminate the callback you're passing to those functions. Long term I would like to see as few synchronous calls as possible though.
- [ ] I spot that the module `request` is required in *events/strawpoll.js*, but don't see it in the project's package.json &mdash; to fix this just run `npm i --save request`
- [ ] Could you remove or stash the changes regarding the *config/constants.js* file? My thoughts are that since it's not really used widely in this PR that maybe it should be shelved until it is used in more places throughout the project. I also think since it looks like it would be mostly used for boolean values (and not really any of the secret values or tmi.client configs) that maybe when it is used in more places throughout the project that it should be moved to a simple json or ini file at the root of the project &mdash; something slightly more user friendly for the broadcaster to go in and tweak. 😄
- [ ] Could you either remove the log files since nothing uses them yet **or** go throughout the project and get all console.log and the tmi.client to use it? I think the module `winston` would be a good for logging if you want to try and fit it into this PR, but otherwise they should be removed and re-introduced in another PR if you want to tackle it.
- [ ] Could you remove the *events/messages.js* file since it's unused right now? I presume this is part of a strategy to move the generic messages Beastie will say to a unified location. I approve of the project moving in this direction, however since this is not really used anywhere yet I would like to keep the master branch's filesystem as lean as possible.

<br><br>

Complete these things or let me know if you're busy and I'll do what I can to make the merge happen. 😃
Thank you for the PR!

**Comment by TalimaVale** [comment]
I have been focusing on theGAME, and just now read through Beastie's PRs. This looks great @shipofgenius ! I had no plans to add these features, and custom commands and polling will be great additions!

I briefly read through your todo list @scryptonite and agree the master branch should be kept as lean as possible, I think that's best going forward.

Unless we're going to test/add more to these new features. In which case this PR could/should be merged into the project in it's own branch? I haven't looked at the code yet, but I'm assuming their pretty straightforward and complete as is, so master branch would be best.

I'm also available to help finish this off if I can help in any way! :)

**Comment by shipofgenius** [comment]
Sounds good. I'll be working on it.

**Pull request closed without merging**
